version: '3.1'

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: synvia
      POSTGRES_USER: user
      POSTGRES_PASSWORD: cacNWDKaZ5Zp89Gp
    ports:
      - 5433:5432
